###########################################
##### 开发环境
###########################################
spring:
  thymeleaf:  ###### thymeleaf配置
    cache: false
    suffix: .html
logging:  #####日志
  path: logs  #存放位置
  level:
    root: info  #打印等级
  config: classpath:config/logback/logback-dev.xml
swagger:
  enabled: true #swagger是否开启
upload:
  filePath: C:/upload/  #文件上传存放路径



