# 服务器配置
server:
  port: 80
  servlet:
    context-path: /aladdin

spring:
#  数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aladdin?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
# mybatis
mybatis:
  mapper-locations: classpath*:***/dao/**/*.xml
  configuration:
#  在控制台打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
